#define MC_LOCK LCTL(LGUI(KC_Q)) // CTRL+CMD+Q is screen lock in macOS 10.13+
#define NUM_LOCK_LED_INDEX 37
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_SAT 0 // white
#define RGB_MATRIX_DEFAULT_VAL 50
